name: dev_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc:
  pull_to_refresh: ^2.0.0  
  equatable: ^2.0.5 
  easy_debounce: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
